services:
  php-apache:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./www/html:/var/www/html
    ports:
      - "8083:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_server2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: warriorschlumec
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadmin2
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"

volumes:
  postgres_data:
