@ -0,0 +1,23 @@
FROM php:8.1-apache

# Povolení modulu rewrite
RUN a2enmod rewrite

# Nastavení výchozí pracovní složky
WORKDIR /var

# Zkopírování obsahu do Apache rootu
COPY . /var

# Nastavení oprávnění
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

# Výchozí index.php
RUN echo "DirectoryIndex index.php" >> /etc/apache2/apache2.conf

# Otevření portu
EXPOSE 80

# Start Apache
CMD ["apache2-foreground"]